# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
import numpy
list=[1,2,3,4,5]
a=np.array([list])
a

array([[1, 2, 3, 4, 5]])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
matrix1=[[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [4]:
a=np.arange(1,18,2)
a.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [5]:
np.random.randint(0,10,10)

array([2, 9, 3, 4, 2, 8, 3, 2, 0, 6])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [6]:

a=np.array([1,2,3,4,5])

a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [7]:
a.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [8]:
a1=np.arange(1,11)
print(a1)
print(a1[2])
print(a1[3])
print(a1[8])

[ 1  2  3  4  5  6  7  8  9 10]
3
4
9


Print alternate elements of that array

In [9]:
print(a1[0:10:2])

[1 3 5 7 9]


Change last 3 elements into 100 using broadcasting and print

In [10]:
a1[7:10]=100
a1

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [11]:
a1=np.arange(1,26)
a2=a1.reshape(5,5)
print(a2)
a2[1:4,1:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])